USE_PKGBUILD=1
include /usr/local/share/luggage/luggage.make
PB_EXTRA_ARGS+= --sign "Developer ID Installer: Clayton Burlison"

TITLE=disable_bluetooth
PACKAGE_VERSION=1.0.0
REVERSE_DOMAIN=com.github.clburlison
PAYLOAD= \
	pack-script-postinstall