#!/usr/bin/python

from Foundation import NSAppleScript, NSBundle

# Frogor hack https://goo.gl/mvQ7Gw
bundle = NSBundle.mainBundle()
info = bundle.localizedInfoDictionary() or bundle.infoDictionary()
# Did you know you can override parts of infoDictionary (Info.plist, after loading) even though Apple says it's read-only?
info['LSUIElement'] = '1'

applescript = '''tell application "System Events"
activate
display dialog "Application '%s' must be quit before we continue. \
Please click continue to quit the application." \
with title "Quit Application" buttons {"Continue", "Cancel"} \
default button "Continue" with icon file "%s"
end tell'''

message = applescript % ('Google Chrome.app', "Applications:Google Chrome.app:Contents:Resources:app.icns")

app = NSAppleScript.alloc().initWithSource_(message)
appresult = app.executeAndReturnError_(None)

if not appresult[0]:
    print "User selected Cancel"
else:
    print "User selected to quit app"
