#!/bin/sh
# Install latest Puppet3 and necessary Ruby Gems needed for a masterless puppet workflow.
# Note: Not all of these gems will be required in all workflows. 
#       However, my workflow does require all of these gems.
#
# Works on 10.11

/usr/bin/gem install -N \
-v '<4.0' puppet \
-n /usr/local/bin

/usr/bin/gem install -N \
r10k sqlite3 hiera-eyaml \
-n /usr/local/bin